@startuml
rectangle "ANY Secure Client" {
  agent "any client" as cRest
  agent "Secure Application" as cAud
  cRest -down.* cAud 
}
rectangle "ANY Secure Server" {
  agent "Secure Application" as sAud
  agent "any server" as sRest
  sRest -down.* sAud
}

agent "Audit Record Repository" as AuditRepository
agent "Audit Consumer" as AuditClient

cRest -right..> sRest : ANY request/response
sAud -down-> AuditRepository: Record Audit Event [ITI-20]
cAud --> AuditRepository: Record Audit Event [ITI-20]
AuditClient -up-> AuditRepository: Retrieve ATNA Audit Event [ITI-81]
@enduml
