@startuml
agent "ANY Secure Client" as Client
agent "ANY Secure Server" as Server
agent "Audit Record Repository" as AuditRepository
agent "Audit Consumer" as AuditClient
Client -right-> Server : ANY request/response
Server -down-> AuditRepository: Record Audit Event
Client --> AuditRepository: Record Audit Event
AuditClient -up-> AuditRepository: Retrieve ATNA Audit Event
@enduml

