# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/docs/sushi/configuration/                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: IHE.ITI.BasicAudit
canonical: http://profiles.ihe.net/ITI/BasicAudit
name: BasicAudit
title: "IHE Basic AuditEvent Implementation Guide"
status: draft
publisher:
  - name: IHE IT Infrastructure Technical Committee
  - url: https://www.ihe.net/ihe_domains/it_infrastructure/
  - email: iti@ihe.net
contact:
  - name: IHE IT Infrastructure Technical Committee
    telecom:
      - system: email
        value: iti@ihe.net
jurisdiction: 'http://unstats.un.org/unsd/methods/m49/m49.htm#001'
copyright: IHE http://www.ihe.net/Governance/#Intellectual_Property
description: >-
  Basic Audit for FHIR REST and operations where the activity includes a subject.
license: CC-BY-SA-4.0
date: 2021-10-28
version: 0.1.0
fhirVersion: 4.0.1
copyrightyear: '2020+'
releaselabel: ci-build

parameters:  # see https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters
  path-resource:
    - fsh-generated/resources
#    - input/examples
#  path-pages:
#    - input/pagecontent
#    - fsh-generated/includes
  show-inherited-invariants: 'false'
  usage-stats-opt-out: 'false'
  logging: progress
  shownav: 'true'
  active-tables: 'false'
  apply-contact: 'true'
  apply-jurisdiction: 'true'
  apply-publisher: 'true'
  apply-version: 'true'
  autoload-resources: 'true'




pages:
  index.md:
    title: Patient Demographics Query for Mobile
    generation: markdown
  volume-1.md:
    title: 1:52 Patient Demographics Query for Mobile (BasicAudit)
    generation: markdown
  content.md:
    title: 3:5.7 Basic Audit Log Patterns
    generation: markdown
  testplan.md:
    title: BasicAudit Test Plan
    generation: markdown
  issues.md:
    title: BasicAudit Open and Closed issues
    generation: markdown
  other.md:
    title: Changes to other Profiles
    generation: markdown
  no.md:
    title: 4:6 Norway National Extension
    generation: markdown

menu:
  BasicAudit Home: index.html
  Volume 1:
    Introduction: volume-1.html
    Actors and Content: volume-1.html#1521-basicaudit-actors-and-content
    Actor Options: volume-1.html#1522-basicaudit-actor-options
    Required Groupings: volume-1.html#1523-basicaudit-required-actor-grouping
    Overview: volume-1.html#1524-basicaudit-overview
    Security Considerations: volume-1.html#1525-basicaudit-security-considerations
    Cross-Profile Considerations: volume-1.html#1526-basicaudit-cross-profile-considerations    
  Volume 3:
    Basic Audit Log Patterns: content.html
  Volume 4:
    Norway: no.html
  Test Plan: testplan.html
  Artifacts: artifacts.html
  Other: other.html
