# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/docs/sushi/configuration/                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: ihe.iti.basicaudit
canonical: https://profiles.ihe.net/ITI/basicaudit
name: IHE_ITI_BasicAudit
title: "IHE ITI Basic AuditEvent Implementation Guide"
#date: 2022-03-01
version: 1.0.2-current
releaselabel: ci-build
#releaselabel: ballot
status: active
publisher:
  - name: IHE IT Infrastructure Technical Committee
  - url: https://www.ihe.net/ihe_domains/it_infrastructure/
  - email: iti@ihe.net
contact:
  - name: IHE IT Infrastructure Technical Committee
    telecom:
      - system: email
        value: iti@ihe.net
jurisdiction: 'http://unstats.un.org/unsd/methods/m49/m49.htm#001'
copyright: IHE http://www.ihe.net/Governance/#Intellectual_Property
description: >-
  The Basic Audit Log Patterns (BasicAudit) **Content Profile** defines some basic and reusable AuditEvent patterns. This includes basic audit log profiles for FHIR RESTful operations, to be used when there is not a more specific audit event defined. Where a more specific audit event can be defined it should be derived off of these basic patterns.
license: CC-BY-SA-4.0
fhirVersion: 4.0.1
copyrightyear: '2022+'

parameters:  # see https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters
  path-resource:
    - fsh-generated/resources
#    - input/examples
#  path-pages:
#    - input/pagecontent
#    - fsh-generated/includes
  show-inherited-invariants: 'false'
  usage-stats-opt-out: 'false'
  logging: progress
  shownav: 'true'
  active-tables: 'false'
  apply-contact: 'true'
  apply-jurisdiction: 'true'
  apply-publisher: 'true'
  apply-version: 'true'
  autoload-resources: 'true'
  path-binary: input/saml


pages:
  index.md:
    title: Basic Audit
    generation: markdown
  volume-1.md:
    title: 1:52 Basic Audit
    generation: markdown
  content.md:
    title: 3:5.7 Basic Audit Log Patterns
    generation: markdown
  testplan.md:
    title: BasicAudit Test Plan
    generation: markdown
  issues.md:
    title: BasicAudit Open and Closed issues
    generation: markdown
  other.md:
    title: Changes to Other Profiles
    generation: markdown
  appendix.md:
    title: AuditEvent use in IHE Implementation Guides
    generation: markdown

menu:
  BasicAudit Home: index.html
  Volume 1:
    Introduction: volume-1.html
    Actors and Content: volume-1.html#1521-basicaudit-actors-and-content
    Actor Options: volume-1.html#1522-basicaudit-actor-options
    Required Groupings: volume-1.html#1523-basicaudit-required-actor-grouping
    Overview: volume-1.html#1524-basicaudit-overview
    Security Considerations: volume-1.html#1525-basicaudit-security-considerations
    Cross-Profile Considerations: volume-1.html#1526-basicaudit-cross-profile-considerations    
  Volume 3:
    Basic Audit Log Patterns: content.html
    -RESTful activities: content.html#3573-restful-activities
    -SAML Security Token: content.html#3574-saml-security-token
    -OAuth Security Token: content.html#3575-oauth-security-token
    -Consent Authorized Decision Audit Message: content.html#3576-consent-authorized-decision-audit-message
    -Privacy Disclosure Audit Message: content.html#3577-privacy-disclosure-audit-message
  Test Plan: testplan.html
  Artifacts: artifacts.html
  Other: 
    Changes to Other Specifications: other.html
    AuditEvent use in Other Profiles: appendix.html
